[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@src/=src/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia_testnet = "${SEPOLIA_TESTNET_RPC_URL}"
mainnet = "${RPC_MAINNET}"

[etherscan]
sepolia_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
